# Spring
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password:
