# Spring
spring:
  profiles:
    active: test
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:../test
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
