# Spring
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test
    username: sa
    password:
  #datasource:
  #  url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DBNAME}?serverTimezone=UTC&characterEncoding=UTF-8
  #  username: ${MYSQL_USERNAME}
  #  password: ${MYSQL_PASSWORD}
  #  driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
